### ISSUE TITLE
Add me to this repo?

### ISSUE THREAD

**Issue by jennybc** [edwindj/whisker#28]
Hi @edwindj. As per our chat, I'm happy to take the lead on getting a release ready. It would be nice to do a few housekeeping tasks during this process, e.g. tag releases, update README & badges, etc.. To that end, maybe you could add me as a collaborator with write or admin permissions. That way I could do things, cc'ing or tagging you for awareness, but not requiring you to be involved in each step.

**Comment by edwindj** [comment]
Hi Jenny,

I have added you to the repo :-), 

Best,

Edwin
