### ISSUE TITLE
R package with whisker as dependency fails CRAN checks on r-devel-windows

### ISSUE THREAD

**Issue by qdread** [edwindj/whisker#37]
I wanted to bring this to your attention. We recently submitted a new release of a package, [rslurm](https://github.com/SESYNC-ci/rslurm), to CRAN that has a strong dependency of `whisker (>=0.3)` (in the `Imports` field of the `DESCRIPTION` file). Unfortunately our package [fails CRAN checks](https://cran.r-project.org/web/checks/check_results_rslurm.html) for the experimental `r-devel` build on Windows (`r-devel-windows-x86_64-gcc10-UCRT`). It looks like this is because `whisker` depends on `markdown` which isn't available on that version of R: https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/whisker-00check.html

Anyway, we really appreciate the work you put into this package and it would be great if we could get this resolved so that we can continue depending on `whisker` in the future. Please let me know if there is anything I can do.

**Comment by edwindj** [comment]
Thanks for the note! I will send a fix to CRAN tomorrow morning!

Best,

Edwin

Op zo 25 apr. 2021 19:20 schreef Quentin Read ***@***.***>:

**Comment by qdread** [comment]
Looks like you fixed it! At any rate, the dependency error is gone now. Thanks!
